;              
CREATE CACHED TABLE DIMACCOUNT(
    SK_ACCOUNTID DECIMAL(11) NOT NULL,
    ACCOUNTID DECIMAL(11) NOT NULL,
    SK_BROKERID DECIMAL(11) NOT NULL,
    SK_CUSTOMERID DECIMAL(11) NOT NULL,
    STATUS VARCHAR(11) NOT NULL,
    ACCOUNTDESC VARCHAR(50),
    TAXSTATUS DECIMAL(1) NOT NULL,
    ISCURRENT BOOLEAN NOT NULL,
    BATCHID DECIMAL(5) NOT NULL,
    EFFECTIVEDATE DATE NOT NULL,
    ENDDATE DATE NOT NULL
);  
CREATE CACHED TABLE DIMBROKER(
    SK_BROKERID DECIMAL(11) NOT NULL,
    BROKERID DECIMAL(11) NOT NULL,
    MANAGERID DECIMAL(11),
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    MIDDLEINITIAL VARCHAR(1),
    BRANCH VARCHAR(50),
    OFFICE VARCHAR(50),
    PHONE VARCHAR(14),
    ISCURRENT BOOLEAN NOT NULL,
    BATCHID DECIMAL(5) NOT NULL,
    EFFECTIVEDATE DATE NOT NULL,
    ENDDATE DATE NOT NULL
);             
CREATE CACHED TABLE DIMCOMPANY(
    SK_COMPANYID DECIMAL(11) NOT NULL,
    COMPANYID DECIMAL(11) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    NAME VARCHAR(60) NOT NULL,
    INDUSTRY VARCHAR(50) NOT NULL,
    SPRATING VARCHAR(4),
    ISLOWGRADE BOOLEAN,
    CEO VARCHAR(100) NOT NULL,
    ADDRESSLINE1 VARCHAR(80),
    ADDRESSSLINE2 VARCHAR(80),
    POSTALCODE VARCHAR(12) NOT NULL,
    CITY VARCHAR(25) NOT NULL,
    STATEPROV VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(24),
    DESCRIPTION VARCHAR(150) NOT NULL,
    FOUNDINGDATE DATE,
    ISCURRENT BOOLEAN NOT NULL,
    BATCHID DECIMAL(5) NOT NULL,
    EFFECTIVEDATE DATE NOT NULL,
    ENDDATE DATE NOT NULL
);  
CREATE CACHED TABLE DIMCUSTOMER(
    SK_CUSTOMERID DECIMAL(11) NOT NULL,
    CUSTOMERID DECIMAL(11) NOT NULL,
    TAXID VARCHAR(20) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    LASTNAME VARCHAR(30) NOT NULL,
    FIRSTNAME VARCHAR(30) NOT NULL,
    MIDDLEINITIAL VARCHAR(1),
    GENDER VARCHAR(1),
    TIER DECIMAL(1),
    DOB DATE NOT NULL,
    ADDRESSLINE1 VARCHAR(80) NOT NULL,
    ADDRESSLINE2 VARCHAR(80),
    POSTALCODE VARCHAR(12) NOT NULL,
    CITY VARCHAR(25) NOT NULL,
    STATEPROV VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(24),
    PHONE1 VARCHAR(30),
    PHONE2 VARCHAR(30),
    PHONE3 VARCHAR(30),
    EMAIL1 VARCHAR(50),
    EMAIL2 VARCHAR(50),
    NATIONALTAXRATEDESC VARCHAR(50),
    NATIONALTAXRATE DECIMAL(6, 5),
    LOCALTAXRATEDESC VARCHAR(50),
    LOCALTAXRATE DECIMAL(6, 5),
    AGENCYID VARCHAR(30),
    CREDITRATING DECIMAL(5),
    NETWORTH DECIMAL(10),
    MARKETINGNAMEPLATE VARCHAR(100),
    ISCURRENT BOOLEAN NOT NULL,
    BATCHID DECIMAL(5) NOT NULL,
    EFFECTIVEDATE DATE NOT NULL,
    ENDDATE DATE NOT NULL
);       
CREATE CACHED TABLE DIMDATE(
    SK_DATEID DECIMAL(11) NOT NULL,
    DATEVALUE DATE NOT NULL,
    DATEDESC VARCHAR(20) NOT NULL,
    CALENDARYEARID DECIMAL(4) NOT NULL,
    CALENDARYEARDESC VARCHAR(20) NOT NULL,
    CALENDARQTRID DECIMAL(5) NOT NULL,
    CALENDARQTRDESC VARCHAR(20) NOT NULL,
    CALENDARMONTHID DECIMAL(6) NOT NULL,
    CALENDARMONTHDESC VARCHAR(20) NOT NULL,
    CALENDARWEEKID DECIMAL(6) NOT NULL,
    CALENDARWEEKDESC VARCHAR(20) NOT NULL,
    DAYOFWEEKNUM DECIMAL(1) NOT NULL,
    DAYOFWEEKDESC VARCHAR(10) NOT NULL,
    FISCALYEARID DECIMAL(4) NOT NULL,
    FISCALYEARDESC VARCHAR(20) NOT NULL,
    FISCALQTRID DECIMAL(5) NOT NULL,
    FISCALQTRDESC VARCHAR(20) NOT NULL,
    HOLIDAYFLAG BOOLEAN
);         
CREATE CACHED TABLE DIMSECURITY(
    SK_SECURITYID DECIMAL(11) NOT NULL,
    SYMBOL VARCHAR(15) NOT NULL,
    ISSUE VARCHAR(6) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    NAME VARCHAR(70) NOT NULL,
    EXCHANGEID VARCHAR(6) NOT NULL,
    SK_COMPANYID DECIMAL(11) NOT NULL,
    SHARESOUTSTANDING DECIMAL(12) NOT NULL,
    FIRSTTRADE DATE NOT NULL,
    FIRSTTRADEONEXCHANGE DATE NOT NULL,
    DIVIDEND DECIMAL(15) NOT NULL,
    ISCURRENT BOOLEAN NOT NULL,
    BATCHID DECIMAL(5) NOT NULL,
    EFFECTIVEDATE DATE NOT NULL,
    ENDDATE DATE NOT NULL
);   
CREATE CACHED TABLE DIMTIME(
    SK_DATEID DECIMAL(11) NOT NULL,
    TIMEVALUE DATE NOT NULL,
    HOURID DECIMAL(2) NOT NULL,
    HOURDESC VARCHAR(20) NOT NULL,
    MINUTEID DECIMAL(2) NOT NULL,
    MINUTEDESC VARCHAR(20) NOT NULL,
    SECONDID DECIMAL(2) NOT NULL,
    SECONDDESC VARCHAR(20) NOT NULL,
    MARKETHOURSFLAG BOOLEAN,
    OFFICEHOURSFLAG BOOLEAN
);
CREATE CACHED TABLE DIMTRADE(
    TRADEID DECIMAL(11) NOT NULL,
    SK_BROKERID DECIMAL(11),
    SK_CREATEDATEID DECIMAL(11) NOT NULL,
    SK_CREATETIMEID DECIMAL(11) NOT NULL,
    SK_CLOSEDATEID DECIMAL(11),
    SK_CLOSETIMEID DECIMAL(11),
    STATUS VARCHAR(10) NOT NULL,
    TYPE VARCHAR(12) NOT NULL,
    CASHFLAG BOOLEAN NOT NULL,
    SK_SECURITYID DECIMAL(11) NOT NULL,
    SK_COMPANYID DECIMAL(11) NOT NULL,
    QUANTITY DECIMAL(6) NOT NULL,
    BIDPRICE DECIMAL(6, 2) NOT NULL,
    SK_CUSTOMERID DECIMAL(11) NOT NULL,
    SK_ACCOUNTID DECIMAL(11) NOT NULL,
    EXECUTEDBY VARCHAR(64) NOT NULL,
    TRADEPRICE DECIMAL(8, 2),
    FEE DECIMAL(10, 2),
    COMMISSION DECIMAL(10, 2),
    TAX DECIMAL(10, 2),
    BATCHID DECIMAL(5) NOT NULL
); 
CREATE CACHED TABLE DIMESSAGE(
    MESSAGEDATEANDTIME TIMESTAMP NOT NULL,
    BATCHID DECIMAL(5) NOT NULL,
    MESSAGESOURCE VARCHAR(30),
    MESSAGETEXT VARCHAR(50) NOT NULL,
    MESSAGETYPE VARCHAR(12) NOT NULL,
    MESSAGEDATA VARCHAR(100)
);     
CREATE CACHED TABLE FACTCASHBALANCES(
    SK_CUSTOMERID DECIMAL(11) NOT NULL,
    SK_ACCOUNTID DECIMAL(11) NOT NULL,
    SK_DATEID DECIMAL(11) NOT NULL,
    CASH DECIMAL(15, 2) NOT NULL,
    BATCHID DECIMAL(5) NOT NULL
);             
CREATE CACHED TABLE FACTHOLDINGS(
    TRADEID DECIMAL(11) NOT NULL,
    CURRENTTRADEID DECIMAL(11) NOT NULL,
    SK_CUSTOMERID DECIMAL(11) NOT NULL,
    SK_ACCOUNTID DECIMAL(11) NOT NULL,
    SK_SECURITYID DECIMAL(11) NOT NULL,
    SK_COMPANYID DECIMAL(11) NOT NULL,
    SK_DATEID DECIMAL(11) NOT NULL,
    SK_TIMEID DECIMAL(11) NOT NULL,
    CURRENTPRICE DECIMAL(8, 2),
    CURRENTHOLDING DECIMAL(6) NOT NULL,
    BATCHID DECIMAL(5) NOT NULL
);             
CREATE CACHED TABLE FACTMARKETHISTORY(
    SK_SECURITYID DECIMAL(11) NOT NULL,
    SK_COMPANYID DECIMAL(11) NOT NULL,
    SK_DATEID DECIMAL(11) NOT NULL,
    PERATIO DECIMAL(10, 2),
    YIELD DECIMAL(5, 2) NOT NULL,
    FIFTYTWOWEEKHIGH DECIMAL(8, 2) NOT NULL,
    SK_FIFTYTWOWEEKHIGHDATE DECIMAL(11) NOT NULL,
    FIFTYTWOWEEKLOW DECIMAL(8, 2) NOT NULL,
    SK_FIFTYTWOWEEKLOWDATE DECIMAL(11) NOT NULL,
    CLOSEPRICE DECIMAL(8, 2) NOT NULL,
    DAYHIGH DECIMAL(8, 2) NOT NULL,
    DAYLOW DECIMAL(8, 2) NOT NULL,
    VOLUME DECIMAL(12) NOT NULL,
    BATCHID DECIMAL(5) NOT NULL
);     
CREATE CACHED TABLE FACTWATCHES(
    SK_CUSTOMERID DECIMAL(11) NOT NULL,
    SK_SECURITYID DECIMAL(11) NOT NULL,
    SK_DATEID_DATEPLACED DECIMAL(11) NOT NULL,
    SK_DATEID_DATEREMOVED DECIMAL(11),
    BATCHID DECIMAL(5) NOT NULL
); 
CREATE CACHED TABLE INDUSTRY(
    IN_ID VARCHAR(2) NOT NULL,
    IN_NAME VARCHAR(50) NOT NULL,
    IN_SC_ID VARCHAR(4) NOT NULL
);        
CREATE CACHED TABLE FINANCIAL(
    SK_COMPANYID DECIMAL(11) NOT NULL,
    FI_YEAR DECIMAL(4) NOT NULL,
    FI_QTR DECIMAL(1) NOT NULL,
    FI_QTR_START_DATE DATE NOT NULL,
    FI_REVENUE DECIMAL(15, 2) NOT NULL,
    FI_NET_EARN DECIMAL(15, 2) NOT NULL,
    FI_BASIC_EPS DECIMAL(10, 2) NOT NULL,
    FI_DILUT_EPS DECIMAL(10, 2) NOT NULL,
    FI_MARGIN DECIMAL(10, 2) NOT NULL,
    FI_INVENTORY DECIMAL(15, 2) NOT NULL,
    FI_ASSETS DECIMAL(15, 2) NOT NULL,
    FI_LIABILITY DECIMAL(15, 2) NOT NULL,
    FI_OUT_BASIC DECIMAL(12) NOT NULL,
    FI_OUT_DILUT DECIMAL(12) NOT NULL
);        
CREATE CACHED TABLE PROSPECT(
    AGENCYID VARCHAR(30) NOT NULL,
    SK_RECORDDATEID DECIMAL(11) NOT NULL,
    SK_UPDATEDATEID DECIMAL(11) NOT NULL,
    BATCHID DECIMAL(5) NOT NULL,
    ISCUSTOMER BOOLEAN NOT NULL,
    LASTNAME VARCHAR(30) NOT NULL,
    FIRSTNAME VARCHAR(30) NOT NULL,
    MIDDLEINITIAL VARCHAR(1),
    GENDER VARCHAR(1),
    ADDRESSLINE1 VARCHAR(80),
    ADDRESSLINE2 VARCHAR(80),
    POSTALCODE VARCHAR(12),
    CITY VARCHAR(25) NOT NULL,
    STATE VARCHAR(25) NOT NULL,
    COUNTRY VARCHAR(24),
    PHONE VARCHAR(30),
    INCOME DECIMAL(9),
    NUMBERCARS DECIMAL(2),
    NUMBERCHILDREN DECIMAL(2),
    MARITALSTATUS VARCHAR(1),
    AGE DECIMAL(3),
    CREDITRATING DECIMAL(4),
    OWNORRENTFLAG VARCHAR(1),
    EMPLOYER VARCHAR(30),
    NUMBERCREDITCARDS DECIMAL(2),
    NETWORTH DECIMAL(12),
    MARKETINGNAMEPLATE VARCHAR(100)
);      
CREATE CACHED TABLE STATUSTYPE(
    ST_ID VARCHAR(4) NOT NULL,
    ST_NAME VARCHAR(10) NOT NULL
);        
CREATE CACHED TABLE TAXRATE(
    TX_ID VARCHAR(4) NOT NULL,
    TX_NAME VARCHAR(50) NOT NULL,
    TX_RATE DECIMAL(6, 5) NOT NULL
);       
CREATE CACHED TABLE TRADETYPE(
    TT_ID VARCHAR(3) NOT NULL,
    TT_NAME VARCHAR(12) NOT NULL,
    TT_IS_SELL DECIMAL(1) NOT NULL,
    TT_IS_MRKT DECIMAL(1) NOT NULL
); 
CREATE CACHED TABLE AUDIT(
    DATASET VARCHAR(20) NOT NULL,
    BATCHID DECIMAL(5),
    DATE DATE,
    ATTRIBUTE VARCHAR(50) NOT NULL,
    VALUE DECIMAL(15),
    DVALUE DECIMAL(15, 5)
);               
